In [8]:
# Example of calculating class probabilities
from math import sqrt
from math import pi
from math import exp

# Split the dataset by class values, returns a dictionary
def separate_by_class(dataset):
	separated = dict()
	for i in range(len(dataset)):
		vector = dataset[i]
		class_value = vector[-1]
		if (class_value not in separated):
			separated[class_value] = list()
		separated[class_value].append(vector)
	print('supper',separated)
	return separated

# Calculate the mean of a list of numbers
def mean(numbers):
	return sum(numbers)/float(len(numbers))

# Calculate the standard deviation of a list of numbers
def stdev(numbers):
	print('std',numbers)
	avg = mean(numbers)
	variance = sum([(x-avg)**2 for x in numbers]) / float(len(numbers)-1)
	return sqrt(variance)

# Calculate the mean, stdev and count for each column in a dataset
def summarize_dataset(dataset):
	summaries = [(mean(column), stdev(column), len(column)) for column in zip(*dataset)]
	del(summaries[-1])
	return summaries

# Split dataset by class then calculate statistics for each row
def summarize_by_class(dataset):
	separated = separate_by_class(dataset)
	summaries = dict()
	for class_value, rows in separated.items():
		summaries[class_value] = summarize_dataset(rows)
	return summaries

# Calculate the Gaussian probability distribution function for x
def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent

# Calculate the probabilities of predicting each class for a given row
def calculate_class_probabilities(summaries, row):
	total_rows = sum([summaries[label][0][2] for label in summaries])
	probabilities = dict()
	print(summaries.items())
	for class_value, class_summaries in summaries.items():
		print('111')

		print(class_value, class_summaries)
		probabilities[class_value] = summaries[class_value][0][2]/float(total_rows)
		for i in range(len(class_summaries)):
			print(class_value,probabilities[class_value])
			mean, stdev, _ = class_summaries[i]

			probabilities[class_value] *= calculate_probability(row[i], mean, stdev)
	return probabilities

# Test calculating class probabilities
dataset = [[3.393533211,2.331273381,0],
	[3.110073483,1.781539638,0],
	[1.343808831,3.368360954,0],
	[3.582294042,4.67917911,0],
	[2.280362439,2.866990263,0],
	[7.423436942,4.696522875,1],
	[5.745051997,3.533989803,1],
	[9.172168622,2.511101045,1],
	[7.792783481,3.424088941,1],
	[7.939820817,0.791637231,1]]
summaries = summarize_by_class(dataset)
probabilities = calculate_class_probabilities(summaries, dataset[0])
print(probabilities)

supper {0: [[3.393533211, 2.331273381, 0], [3.110073483, 1.781539638, 0], [1.343808831, 3.368360954, 0], [3.582294042, 4.67917911, 0], [2.280362439, 2.866990263, 0]], 1: [[7.423436942, 4.696522875, 1], [5.745051997, 3.533989803, 1], [9.172168622, 2.511101045, 1], [7.792783481, 3.424088941, 1], [7.939820817, 0.791637231, 1]]}
std (3.393533211, 3.110073483, 1.343808831, 3.582294042, 2.280362439)
std (2.331273381, 1.781539638, 3.368360954, 4.67917911, 2.866990263)
std (0, 0, 0, 0, 0)
std (7.423436942, 5.745051997, 9.172168622, 7.792783481, 7.939820817)
std (4.696522875, 3.533989803, 2.511101045, 3.424088941, 0.791637231)
std (1, 1, 1, 1, 1)
dict_items([(0, [(2.7420144012, 0.9265683289298018, 5), (3.0054686692, 1.1073295894898725, 5)]), (1, [(7.6146523718, 1.2344321550313704, 5), (2.9914679790000003, 1.4541931384601618, 5)])])
111
0 [(2.7420144012, 0.9265683289298018, 5), (3.0054686692, 1.1073295894898725, 5)]
0 0.5
0 0.1681279594903111
111
1 [(7.6146523718, 1.2344321550313704, 5), (2.9914

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [6]:
hduDF = pd.read_csv('heart_disease_uci.csv')
labler = LabelEncoder()
labledDF = hduDF.copy()
labledDF['sex'] = labler.fit_transform(labledDF['sex'])
labledDF['dataset'] = labler.fit_transform(labledDF['dataset'])
labledDF['cp'] = labler.fit_transform(labledDF['cp'])
labledDF['fbs'] = labler.fit_transform(labledDF['fbs'])
labledDF['restecg'] = labler.fit_transform(labledDF['restecg'])
labledDF['exang'] = labler.fit_transform(labledDF['exang'])
labledDF['slope'] = labler.fit_transform(labledDF['slope'])
labledDF['thal'] = labler.fit_transform(labledDF['thal'])
labledDF = labledDF.replace(np.nan,-1)
labledDF

id  age  sex  dataset  cp  trestbps   chol  fbs  restecg  thalch  exang  \
0      1   63    1        0   3     145.0  233.0    1        0   150.0      0   
1      2   67    1        0   0     160.0  286.0    0        0   108.0      1   
2      3   67    1        0   0     120.0  229.0    0        0   129.0      1   
3      4   37    1        0   2     130.0  250.0    0        1   187.0      0   
4      5   41    0        0   1     130.0  204.0    0        0   172.0      0   
..   ...  ...  ...      ...  ..       ...    ...  ...      ...     ...    ...   
915  916   54    0        3   0     127.0  333.0    1        2   154.0      0   
916  917   62    1        3   3      -1.0  139.0    0        2    -1.0      2   
917  918   55    1        3   0     122.0  223.0    1        2   100.0      0   
918  919   58    1        3   0      -1.0  385.0    1        0    -1.0      2   
919  920   62    1        3   1     120.0  254.0    0        0    93.0      1   

     oldpeak  slope   ca  thal  num  
0        2.3      0  0.0     0    0  
1        1.5      1  3.0     1    2  
2        2.6      1  2.0     2    1  
3        3.5      0  0.0     1    0  
4        1.4      2  0.0     1    0  
..       ...    ...  ...   ...  ...  
915      0.0      3 -1.0     3    1  
916     -1.0      3 -1.0     3    0  
917      0.0      3 -1.0     0    2  
918     -1.0      3 -1.0     3    0  
919      0.0      3 -1.0     3    1  

[920 rows x 16 columns]

In [7]:

x = labledDF.iloc[:,:-1]
y = labledDF.iloc[:,-1]
splitNum = int(len(labledDF['cp'])*0.8)
x_train = labledDF.iloc[:splitNum,:-1]
x_test = labledDF.iloc[splitNum:,:-1]
y_train = labledDF.iloc[:splitNum,-1]
y_test = labledDF.iloc[splitNum:,-1]

In [9]:
def myNBayesFit(xtrain,xtest):
    pass

def getMeanOfFeature(strOrIndex,DataFrame):
    return np.mean(DataFrame[strOrIndex])

def getSTDOfFeature(strOrIndex,DataFrame):
    return np.std(DataFrame[strOrIndex])

def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent

print(getMeanOfFeature('sex',x_train),getSTDOfFeature('sex',x_train))


for column in x_train.columns:
     

0.7445652173913043 0.43610532494151455


In [33]:
def summarizeByClass(dataset):
    separated = separateByClass(dataset)
    summaries = {}
    for classValue, instances in separated.items():
        summaries[classValue] = summarize(instances)
    return summaries

def summarize(dataset):
    summaries = [(mean_list(attribute), stdev_list(attribute)) for attribute in zip(*dataset)]
    del summaries[-1]
    return summaries

def separateByClass(dataset):
    separated = {}
    for i in range(len(dataset)):
        vector = dataset[i]
        if (vector[-1] not in separated):
            separated[vector[-1]] = []
            separated[vector[-1]].append(vector)
    return separated

def calculateClassProbabilities(summaries, inputVector):
    probabilities = {}
    for j,classSummaries in enumerate(summaries):
        probabilities[j] = 1
        for i in range(len(classSummaries)):
            mean, stdev = classSummaries[i]
            x = inputVector[i]
            probabilities[j] *= calculate_probability(x, mean, stdev)
    return probabilities

def calculate_probability(x, mean, stdev):
	exponent = exp(-((x-mean)**2 / (2 * stdev**2 )))
	return (1 / (sqrt(2 * pi) * stdev)) * exponent

def predict(summaries, inputVector):
    probabilities = calculateClassProbabilities(summaries, inputVector)
    bestLabel, bestProb = None, -1
    for classValue, probability in probabilities.items():
        if bestLabel is None or probability > bestProb:
            bestProb = probability
            bestLabel = classValue
    return bestLabel

def getPredictions(summaries, testSet):
    predictions = []
    for i in range(len(testSet)):
        result = predict(summaries, testSet[i])
        predictions.append(result)
    return predictions

# Calculate the mean of a list of numbers
def mean_list(numbers):
	return np.mean(numbers)

# Calculate the standard deviation of a list of numbers
def stdev_list(numbers):
	np.std(numbers)


hduDF = pd.read_csv('heart_disease_uci.csv')
labler = LabelEncoder()
labledDF = hduDF.copy()
labledDF['sex'] = labler.fit_transform(labledDF['sex'])
labledDF['dataset'] = labler.fit_transform(labledDF['dataset'])
labledDF['cp'] = labler.fit_transform(labledDF['cp'])
labledDF['fbs'] = labler.fit_transform(labledDF['fbs'])
labledDF['restecg'] = labler.fit_transform(labledDF['restecg'])
labledDF['exang'] = labler.fit_transform(labledDF['exang'])
labledDF['slope'] = labler.fit_transform(labledDF['slope'])
labledDF['thal'] = labler.fit_transform(labledDF['thal'])
labledDF = labledDF.replace(np.nan,-1)
splitNum = int(len(labledDF['cp'])*0.8)

x = labledDF.iloc[:,1:-1]
y = labledDF.iloc[:,-1]
train = labledDF.iloc[:splitNum,1:]
test = labledDF.iloc[splitNum:,1:]
x_train = labledDF.iloc[:splitNum,1:-1]
x_test = labledDF.iloc[splitNum:,1:-1]
y_train = labledDF.iloc[:splitNum,-1]
y_test = labledDF.iloc[splitNum:,-1]
#print('Split {0} rows into train = {1} and test = {2} rows'.format(len(dataset),len(trainingSet),len(testSet)))
#prepare model
summaries = train.drop_duplicates().to_numpy()
print(summaries)

#test model

predictions = getPredictions(summaries, test.to_numpy())
#accuracy = getAccuracy(testSet, predictions)
#print('Accuracy: {0}%'.format(accuracy))


[[63.  1.  0. ...  0.  0.  0.]
 [67.  1.  0. ...  3.  1.  2.]
 [67.  1.  0. ...  2.  2.  1.]
 ...
 [63.  1.  3. ... -1.  3.  1.]
 [57.  1.  3. ... -1.  3.  1.]
 [62.  1.  3. ... -1.  3.  0.]]


TypeError: cannot unpack non-iterable numpy.float64 object